import React, { useEffect, useRef, useState } from 'react';
import { ChevronLeft, FileText, Folder, Check } from 'lucide-react';

const sections = [
  ['overview', '1. Executive Overview'], ['architecture', '2. System Architecture & Processing Pipeline'],
  ['dissection', '3. Packet Ingestion & Protocol Dissection Engine'], ['classifier', '4. AI Traffic Classification Engine'],
  ['compliance', '5. NIST SP 800-77 Compliance Engine'], ['anomaly', '6. Behavioral Anomaly Detection Engine'],
  ['pqc', '7. Post-Quantum Cryptography Readiness Assessment'], ['testbed', '8. Multi-Node Testbed Infrastructure'], ['api', '9. REST API Reference'],
];
const SectionHeading = ({ id, children }) => <h2 id={id} className="gdoc-section-heading">{children}</h2>;
const Subheading = ({ children }) => <h3 className="gdoc-subheading">{children}</h3>;
const BulletList = ({ children }) => <ul className="gdoc-list">{children}</ul>;

export default function TechnicalDocsTab() {
  const [activeSection, setActiveSection] = useState('overview');
  const [title, setTitle] = useState('PrivComm — IPsec VPN Intelligence & Traffic Classification Platform');
  const docRef = useRef(null);

  useEffect(() => {
    const root = docRef.current;
    if (!root) return undefined;
    const observer = new IntersectionObserver((entries) => {
      const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio);
      if (visible[0]) setActiveSection(visible[0].target.id);
    }, { root, rootMargin: '-12% 0px -70% 0px', threshold: [0.1, 0.35, 0.6] });
    sections.forEach(([id]) => { const element = document.getElementById(id); if (element) observer.observe(element); });
    return () => observer.disconnect();
  }, []);
  const jumpTo = (id) => { setActiveSection(id); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); };
  return (
    <div className="gdoc-shell">
      <div className="gdoc-topbar">
        <div className="gdoc-file-icon"><FileText size={25} strokeWidth={1.7} /></div>
        <div className="gdoc-title-wrap"><input aria-label="Document title" value={title} onChange={(event) => setTitle(event.target.value)} /><div className="gdoc-file-meta"><span>Starred</span><span>Last edit was a few seconds ago</span></div></div>
      </div>
      <div className="gdoc-workspace">
        <aside className="gdoc-outline" aria-label="Document outline"><div className="gdoc-outline-title"><span>Document outline</span><button title="Collapse outline"><ChevronLeft size={16} /></button></div><div className="gdoc-outline-list">{sections.map(([id, label]) => <button key={id} className={`gdoc-outline-item ${activeSection === id ? 'active' : ''}`} onClick={() => jumpTo(id)}>{label}</button>)}</div><div className="gdoc-outline-footer"><Folder size={15} /> Technical documentation</div></aside>
        <div className="gdoc-editor-wrap">
          <main className="gdoc-editor" ref={docRef}><article className="gdoc-page">
            <header className="gdoc-cover"><div className="gdoc-cover-kicker">TECHNICAL DOCUMENTATION</div><h1>PrivComm — IPsec VPN Intelligence &amp;<br />Traffic Classification Platform</h1><p className="gdoc-lede">A production-grade platform for analyzing, assessing, and securing encrypted VPN infrastructure in real time.</p><div className="gdoc-cover-rule" /><div className="gdoc-cover-grid"><span><b>Document owner</b>PrivComm Security Engineering</span><span><b>Classification</b>Internal technical reference</span><span><b>Updated</b>October 2026</span></div></header>
            <SectionHeading id="overview">1. Executive Overview</SectionHeading><p><strong>PrivComm</strong> is a production-grade IPsec VPN Intelligence and Traffic Classification platform designed to analyze, assess, and secure encrypted VPN infrastructures in real time.</p><p>The platform combines:</p><BulletList><li>Deep Protocol Dissection</li><li>AI-Powered Traffic Classification</li><li>Automated Security Assessment</li><li>Compliance Validation</li><li>Behavioral Anomaly Detection</li></BulletList><p>It provides actionable security intelligence without decrypting protected VPN payloads.</p><Subheading>Core Capabilities</Subheading><Subheading>Deep Packet Dissection</Subheading><p>Extracts observable IPsec and IKE parameters including:</p><BulletList><li>IKEv1 / IKEv2 Protocol Version</li><li>Security Parameter Index (SPI)</li><li>Encryption Algorithms</li><li>Integrity Algorithms</li><li>Diffie-Hellman Groups</li><li>Perfect Forward Secrecy (PFS)</li><li>Tunnel &amp; Transport Modes</li></BulletList><Subheading>AI Traffic Classification</Subheading><p>Uses a trained XGBoost classifier to identify encrypted application traffic based on statistical flow behavior.</p><p>Supported classes include:</p><BulletList><li>Chat</li><li>VoIP</li><li>Streaming</li><li>P2P</li><li>File Transfer</li><li>Web Browsing</li><li>DNS</li><li>Gaming</li><li>Other encrypted traffic categories</li></BulletList><Subheading>Automated Compliance Assessment</Subheading><p>Evaluates VPN configurations against:</p><BulletList><li>NIST SP 800-77 Rev.1</li><li>FIPS 140-3</li><li>Post-Quantum Cryptography Readiness Standards</li></BulletList>
            <SectionHeading id="architecture">2. System Architecture &amp; Processing Pipeline</SectionHeading><p>PrivComm separates protocol analysis, machine learning, compliance validation, and reporting into independent processing stages.</p><Subheading>End-to-End Workflow</Subheading><div className="gdoc-workflow"><span>PCAP File / Live VPN Stream</span><b>↓</b><span>Packet Ingestion Engine</span><b>↓</b><span>Protocol Dissection Layer<br /><small>(TShark / Scapy)</small></span><b>↓</b><span>Feature Extraction Engine<br /><small>(28 Statistical Features)</small></span><div className="gdoc-branch"><span>ML Engine</span><span>Compliance Engine</span></div><b>↓</b><span>Risk Assessment Layer</span><b>↓</b><span>Reports &amp; Dashboard</span></div><Subheading>Major Components</Subheading><BulletList><li>Packet Ingestion and Protocol Dissection</li><li>Machine Learning Classification</li><li>Compliance and Risk Assessment</li><li>Behavioral Monitoring and Reporting</li></BulletList>
            <SectionHeading id="dissection">3. Packet Ingestion &amp; Protocol Dissection Engine</SectionHeading><p>PrivComm utilizes:</p><BulletList><li>TShark</li><li>Scapy</li></BulletList><p>for structured packet analysis.</p><Subheading>Protocol Coverage</Subheading><BulletList><li>IKE Handshake Analysis</li><li>ESP Analysis</li><li>Tunnel Detection</li><li>Security Parameter Extraction</li></BulletList><Subheading>Observable Parameters</Subheading><p>The engine extracts:</p><BulletList><li>IKE Version</li><li>Initiator SPI</li><li>Responder SPI</li><li>Encryption Algorithms</li><li>Integrity Algorithms</li><li>PRF Algorithms</li><li>Diffie-Hellman Groups</li><li>Exchange Types</li><li>Encapsulation Mode</li></BulletList><Subheading>Zero-Payload Inspection Model</Subheading><p>PrivComm never decrypts ESP payloads. Instead, analysis is performed using:</p><BulletList><li>Protocol Metadata</li><li>Cryptographic Negotiation Parameters</li><li>Packet Timing Characteristics</li><li>Statistical Flow Features</li></BulletList><p>This ensures privacy-preserving security assessment.</p>
            <SectionHeading id="classifier">4. AI Traffic Classification Engine</SectionHeading><p>The machine learning subsystem classifies encrypted traffic without payload inspection.</p><Subheading>Model Used</Subheading><p><strong>XGBoost Multi-Class Classifier</strong></p><Subheading>Feature Set</Subheading><p>The model uses 28 statistical flow features including:</p><BulletList><li>Duration</li><li>Total FIAT / BIAT</li><li>Min, max, and mean FIAT / BIAT</li><li>Flow packets per second</li><li>Flow bytes per second</li><li>Flow inter-arrival times</li><li>Active and idle time</li><li>Bytes per packet</li><li>FIAT/BIAT ratio</li><li>Log duration and throughput features</li></BulletList><Subheading>Training Configuration</Subheading><p>Dataset split:</p><BulletList><li>Training: 70%</li><li>Validation: 15%</li><li>Testing: 15%</li></BulletList><p className="gdoc-code-line">n_estimators = 400<br />max_depth = 8<br />learning_rate = 0.08<br />objective = multi:softprob</p><Subheading>Output</Subheading><p>The model predicts:</p><BulletList><li>Traffic Class</li><li>Classification Confidence</li><li>Probability Distribution</li></BulletList><p>across 14 encrypted application categories.</p>
            <SectionHeading id="compliance">5. NIST SP 800-77 Compliance Engine</SectionHeading><p>PrivComm evaluates VPN configurations using predefined security policies.</p><table className="gdoc-table"><thead><tr><th>Policy ID</th><th>Requirement</th><th>Benchmark</th></tr></thead><tbody><tr><td>POL-01</td><td>Protocol Modernity</td><td>IKEv2 Required</td></tr><tr><td>POL-02</td><td>Encryption Strength</td><td>AES-GCM Preferred</td></tr><tr><td>POL-03</td><td>Diffie-Hellman Security</td><td>DH Group ≥ 14</td></tr><tr><td>POL-04</td><td>Perfect Forward Secrecy</td><td>Mandatory</td></tr><tr><td>POL-05</td><td>Integrity Protection</td><td>MD5 &amp; SHA1 Rejected</td></tr><tr><td>POL-06</td><td>Encapsulation Mode</td><td>Tunnel Mode Preferred</td></tr></tbody></table><Subheading>Compliance Outputs</Subheading><BulletList><li>Security Score</li><li>Risk Score</li><li>Policy Violations</li><li>Recommended Remediations</li></BulletList>
            <SectionHeading id="anomaly">6. Behavioral Anomaly Detection Engine</SectionHeading><p>PrivComm continuously monitors VPN telemetry and identifies unusual behavior patterns.</p><Subheading>Detection Capabilities</Subheading><BulletList><li>Replay Attacks</li><li>Traffic Burst Anomalies</li><li>Tunnel Instability</li><li>Session Drift</li><li>Sequence Number Violations</li><li>High-Entropy Exfiltration Patterns</li></BulletList><Subheading>Methodology</Subheading><p>Uses historical VPN behavior baselines and anomaly detection models to identify deviations from expected activity.</p>
            <SectionHeading id="pqc">7. Post-Quantum Cryptography Readiness Assessment</SectionHeading><p>PrivComm evaluates readiness for next-generation cryptographic standards.</p><Subheading>Assessment Areas</Subheading><BulletList><li>Hybrid Key Exchange Support</li><li>ML-KEM (Kyber) Readiness</li><li>RFC 9370 Compatibility</li><li>Quantum Vulnerability Assessment</li></BulletList><Subheading>Identifies</Subheading><p>Potential exposure to:</p><p><strong>Harvest Now, Decrypt Later (HNDL) attacks.</strong></p>
            <SectionHeading id="testbed">8. Multi-Node Testbed Infrastructure</SectionHeading><p>PrivComm includes an isolated IPsec VPN testbed for protocol validation and attack simulation.</p><Subheading>Node Topology</Subheading><table className="gdoc-table"><thead><tr><th>Node</th><th>Address</th><th>Role</th></tr></thead><tbody><tr><td>Initiator</td><td>192.168.56.10</td><td>VPN Client</td></tr><tr><td>Responder</td><td>192.168.56.20</td><td>VPN Gateway</td></tr><tr><td>Observer</td><td>192.168.56.30</td><td>Monitoring Node</td></tr></tbody></table><Subheading>Supported Activities</Subheading><BulletList><li>Tunnel Establishment</li><li>Traffic Injection</li><li>Packet Capture</li><li>Security Assessment</li><li>Attack Simulation</li></BulletList><div className="gdoc-callout"><strong>Future Roadmap</strong><p>Enterprise deployment support through Docker Containers, Kubernetes, AWS, Microsoft Azure, and Google Cloud Platform with scalable packet capture and monitoring infrastructure.</p></div>
            <SectionHeading id="api">9. REST API Reference</SectionHeading><table className="gdoc-table"><thead><tr><th>Method</th><th>Endpoint</th><th>Description</th></tr></thead><tbody><tr><td>POST</td><td>/analyze/protocol</td><td>Upload and analyze PCAP files</td></tr><tr><td>GET</td><td>/analyze/sample</td><td>Retrieve compliant VPN assessment</td></tr><tr><td>GET</td><td>/analyze/sample-weak</td><td>Retrieve non-compliant VPN assessment</td></tr><tr><td>GET</td><td>/api/history</td><td>View historical assessments</td></tr><tr><td>GET</td><td>/reports/download-html</td><td>Download executive audit report</td></tr></tbody></table><Subheading>Key Features Summary</Subheading><div className="gdoc-check-list">{['Deep IPsec Protocol Analysis', 'AI-Powered Encrypted Traffic Classification', 'NIST Compliance Validation', 'Behavioral Anomaly Detection', 'Post-Quantum Readiness Assessment', 'Risk & Security Scoring', 'Live VPN Monitoring', 'Multi-Node Testbed Validation'].map((item) => <div key={item}><Check size={14} /> {item}</div>)}</div><footer className="gdoc-page-footer">PrivComm technical documentation <span>•</span> Internal reference</footer>
          </article></main>
        </div>
      </div>
    </div>
  );
}
